### ISSUE TITLE
is elastalert service started?

### ISSUE THREAD

**Issue by hasnat** [bitsensor/elastalert#12]
docker files starts server via npm start,
I see further down it spawns some python processes which I suspect would be running elastalert tests from UI
my question is if we are starting the elastalert service 
e.g. something like 
`python /opt/elastalert/elastalert/elastalert.py --debug --config /opt/elastalert/config.yaml`

as currently I am using following as docker-compose to make both ui and elastalert (deamon) work
```
elastalert:
    restart: always
    hostname: elastalert
    container_name: elastalert
    image: bitsensor/elastalert
    volumes:
      - "${CONTAINERS_SHARED_DIR}/elastalert/config/config.yaml:/opt/elastalert/config.yaml"
      - "${CONTAINERS_SHARED_DIR}/elastalert/rules:/opt/elastalert/rules"
      - "${CONTAINERS_SHARED_DIR}/elastalert/ui/config.json:/opt/elastalert-server/config/config.json"
    entrypoint: ""
    command:
      - sh
      - -c
      - |
          cd /opt/elastalert-server
          nohup npm start &
          python /opt/elastalert/elastalert/elastalert.py --debug --config /opt/elastalert/config.yaml
```

am I missing something here or is this expected behaviour?
