### ISSUE TITLE
Zabbix alert module error

### ISSUE THREAD

**Issue by himanshurajput32** [bitsensor/elastalert#144]
Hi,

I'm using docker image bitsensor/elastalert:3.0.0-beta.1 to run the elastalert server. I created a new alert using zabbix as an alert module. Here is the my rule file -

`es_host: es_server_address
es_port: 9200
name: test-rule
type: frequency
num_events: 1
timeframe:
seconds: 10
filter:

query:
query_string:
query: "cs-method:POST"
index: logstash*
timestamp_field: "@timestamp"
alert:
zabbix
zbx_sender_host: zabbix_server_address
zbx_sender_port: 10051
zbx_host: elastalert-server
zbx_item: elastalert-item`
Now I'm getting the following error in elastalert server logs -
12:02:11.551Z ERROR elastalert-server: ProcessController: ERROR:root:Could not load rule rules/test-rule.yaml: Error initiating alert ['zabbix']: Could not import module zabbix: need more than 1 value to unpack 12:02:11.568Z ERROR elastalert-server: ProcessController: ERROR:root:Error connecting to SMTP host: {}
Can anyone help me to solve this error?

**Comment by nsano-rururu** [comment]
@himanshurajput32 


Currently, there is a bug in the ElastAlert body and alerts to zabbix do not work properly. 
Since there is a pull request that modified ElastAlert 0.2.1, 
it is necessary to create a Docker image with ElastAlert 0.2.1, 
mount the modified file at startup with docker-compose, and start it.

>zbx_item: elastalert-item`

zbx_item should give an error unless changed to zbx_key
I got an error and changed.

In the source code, it is zbx_key. I think it's a mistake in the documentation.
https://github.com/Yelp/elastalert/blob/master/elastalert/zabbix.py#L56
>self.zbx_key = self.rule.get('zbx_key')

```
mkdir elastalert-docker-wk
cd elastlaert-docker-wk
git clone https://github.com/bitsensor/elastalert.git
vi Dockerfile
```

**Dockerfile**

```
FROM alpine:3.11 as py-ea
ARG ELASTALERT_VERSION=v0.2.1
ENV ELASTALERT_VERSION=${ELASTALERT_VERSION}
# URL from which to download Elastalert.
ARG ELASTALERT_URL=https://github.com/Yelp/elastalert/archive/$ELASTALERT_VERSION.zip
ENV ELASTALERT_URL=${ELASTALERT_URL}
# Elastalert home directory full path.
ENV ELASTALERT_HOME /opt/elastalert

WORKDIR /opt

RUN apk add --update --no-cache ca-certificates openssl-dev openssl python3-dev python3 py3-pip py3-yaml libffi-dev gcc musl-dev wget && \
# Download and unpack Elastalert.
    wget -O elastalert.zip "${ELASTALERT_URL}" && \
    unzip elastalert.zip && \
    rm elastalert.zip && \
    mv e* "${ELASTALERT_HOME}"

WORKDIR "${ELASTALERT_HOME}"

# Sync requirements.txt and setup.py & update py-zabbix #2818 (https://github.com/Yelp/elastalert/pull/2818)
# Install Elastalert.
RUN sed -i 's/PyYAML>=3.12/PyYAML>=5.1/g' setup.py && \
    sed -e "30i         'py-zabbix>=1.1.3'," setup.py && \
    python3 setup.py install

FROM node:14-alpine
LABEL maintainer="BitSensor <dev@bitsensor.io>"
# Set timezone for this container
ENV TZ Etc/UTC

RUN apk add --update --no-cache curl tzdata python3 make libmagic && \
    ln -s /usr/bin/python3 /usr/bin/python

COPY --from=py-ea /usr/lib/python3.8/site-packages /usr/lib/python3.8/site-packages
COPY --from=py-ea /opt/elastalert /opt/elastalert
COPY --from=py-ea /usr/bin/elastalert* /usr/bin/

WORKDIR /opt/elastalert-server
COPY . /opt/elastalert-server

RUN npm install --production --quiet
COPY config/elastalert.yaml /opt/elastalert/config.yaml
COPY config/elastalert-test.yaml /opt/elastalert/config-test.yaml
COPY config/config.json config/config.json
COPY rule_templates/ /opt/elastalert/rule_templates
COPY elastalert_modules/ /opt/elastalert/elastalert_modules

# Add default rules directory
# Set permission as unpriviledged user (1000:1000), compatible with Kubernetes
RUN mkdir -p /opt/elastalert/rules/ /opt/elastalert/server_data/tests/ \
    && chown -R node:node /opt

USER node

EXPOSE 3030
ENTRYPOINT ["npm", "start"]
```

**Docker build**

```
docker build -t elastalert:0.2.1 .
```

**Download zabbix bug pull requested file**

```
# in the same place as docker-compose.yml
mkdir -p elastalert/patch
cd elastalert/patch
# Bugfix and better error handling on zabbix alerter #2640(https://github.com/Yelp/elastalert/pull/2640)
# elastalert/loaders.py
wget https://raw.githubusercontent.com/Yelp/elastalert/7466eb3f195ef8f039e4d472d16285e493e948ab/elastalert/loaders.py

# elastalert/zabbix.py
wget https://raw.githubusercontent.com/Yelp/elastalert/7466eb3f195ef8f039e4d472d16285e493e948ab/elastalert/zabbix.py
````

**An example ElastAlert in docker-compose.yml**

```
  elastalert:
    container_name: elastalert
    image: elastalert:0.2.1
    ports:
      - 3030:3030
      - 3333:3333
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./elastalert/config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./elastalert/config/api.config.json:/opt/elastalert-server/config/config.json
      - ./elastalert/rules:/opt/elastalert/rules
      - ./elastalert/rule_templates:/opt/elastalert/rule_templates
      - ./elastalert/patch/zabbix.py:/opt/elastalert/elastalert/zabbix.py
      - ./elastalert/patch/loaders.py:/opt/elastalert/elastalert/loaders.py 
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s
```
