### ISSUE TITLE
elastalert-create-index 

### ISSUE THREAD

**Issue by psganeshk** [bitsensor/elastalert#191]
Traceback (most recent call last):
  File "/usr/local/bin/elastalert-create-index", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'stomp.py>=4.1.17' distribution was not found and is required by elastalert

**Comment by nsano-rururu** [comment]
I don't know the version of Elasticsearch and which ElastAlertServer you are using, so I can't answer. Because it's not Esper

ElastAlert Server Docker Images

| Docker image name    | tag| ElastAlert |Elasticsearch 7 Support|   Remarks    |
|:-------------------|:----:|:----------:|:----------:|:-----------|
|[bitsensor/elastalert](https://hub.docker.com/r/bitsensor/elastalert/)|2.0.1 |0.1.39|×||
|[bitsensor/elastalert](https://hub.docker.com/r/bitsensor/elastalert/)|lastet|0.1.39|×||
|[bitsensor/elastalert](https://hub.docker.com/r/bitsensor/elastalert/)|3.0.0-beta.0|0.2.0b2|〇||
|[bitsensor/elastalert](https://hub.docker.com/r/bitsensor/elastalert/)|3.0.0-beta.1|0.2.0b2|〇||
|[servercentral/elastalert](https://hub.docker.com/r/servercentral/elastalert)|latest|0.2.1|〇|bitsensor/elastalert fork<br>Customize<br>bugfix<br>Python 3.6|
|[daichi703n/elastalert](https://hub.docker.com/r/daichi703n/elastalert)|0.2.1-dev2|0.2.1|〇|servercentral/elastalert fork<br>Customize<br>bugfix<br>Python 3.6|
|[praecoapp/elastalert-server](https://hub.docker.com/r/praecoapp/elastalert-server)|latest|0.2.4|〇|servercentral/elastalert fork<br>Customize<br>bugfix<br>Library Update<br>Python 3.8|

**Comment by nsano-rururu** [comment]
The development of bitsensor/elastalert is over, so don't expect any more support

**Comment by psganeshk** [comment]
Is it possible to install elastalert offline and if possible please share the steps

**Comment by nsano-rururu** [comment]
I've only used ElastAlert with docker, so I've never installed it directly. Information is provided only. Please understand.

**Installation of Python 3.6 For Amazon Linux 2**

```
# 'Development Tools' is a package equivalent to build-essential in yum
sudo yum -y groupinstall 'Development Tools' 

# libffi-devel is the equivalent package of libffi-dev in yum
# openssl-devel is the equivalent package of libssl-dev in yum
sudo yum -y install python3-devel python3-libs python3-setuptools libffi-devel openssl-devel

# Python Version Check
python3 -V

# Python3.7 Create virtual environment
python3 -m venv ~/py37/

# Python3.7 Virtual environment switching
source ~/py37/bin/activate

```

**Installation of Python 3.6 For Ubuntu 18.04 LTS**

```
sudo apt update
sudo apt upgrade
sudo apt install -y build-essential python3.6-dev libffi-dev libssl-dev python3-pip python3-venv

# Python3.6 Create virtual environment
python3.6 -m venv ~/py36/

# Python3.6 Virtual environment switching
source ~/py36/bin/activate
```
**Installation of Python 3.6 For Ubuntu 20.04 LTS**

```
sudo apt update
sudo apt upgrade
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt -y install build-essential python3.6 python3.6-dev python3-pip libffi-dev libssl-dev python3.6-venv

# Python3.6 Create virtual environment
python3.6 -m venv ~/py36/

# Python3.6 Virtual environment switching
source ~/py36/bin/activate
```

**Installation of Python 3.6 For CentOS 7**

```
sudo yum -y groupinstall 'Development Tools'
sudo yum -y install python3-devel python3-libs python3-setuptools  python3-pip libffi-devel openssl-devel

# Python3.6 Create virtual environment
python3 -m venv ~/py36/

# Python3.6 Virtual environment switching
source ~/py36/bin/activate
```

**Installation of Python 3.6 For CentOS 8**

```
sudo dnf group install "Development Tools"
sudo dnf install python36 python3-devel python3-setuptools python3-libs python3-pip libffi-devel openssl-devel

# Python3.6 Create virtual environment
python3 -m venv ~/py36/

# Python3.6 Virtual environment switching
source ~/py36/bin/activate
```

**Please refer to the following documents for installation of ElastAlert**

Running ElastAlert for the First Time
https://elastalert.readthedocs.io/en/latest/running_elastalert.html

**other info**

Installing and configuring ElastAlert, ElastAlert-Server and Praeco
https://medium.com/@ibrahim.ayadhi/hello-and-welcome-to-our-new-article-which-will-be-covering-the-alerting-part-in-our-socaas-136cf6258c49

**Comment by nsano-rururu** [comment]
docker-compose  example

elasticsearch:7.7.0
kibana:7.7.0
praecoapp/praeco:latest
praecoapp/elastalert-server:latest

praeco/nginx_config/default.conf
https://github.com/johnsusek/praeco/blob/master/nginx_config/default.conf
praeco/nginx_config/nginx.conf
https://github.com/johnsusek/praeco/blob/master/nginx_config/nginx.conf
praeco/public/favicon.ico
https://github.com/johnsusek/praeco/blob/master/public/favicon.ico
praeco/public/index.html
https://github.com/johnsusek/praeco/blob/master/public/index.html
praeco/public/js/cron-ui.min.js
https://github.com/johnsusek/praeco/blob/master/public/js/cron-ui.min.js

```
/home/sano/dkwork2/es
|--Dockerfiles
|  |--Dockerfile.elastalert
|--docker-compose.yml
|--es
|  |--config
|  |  |--elasticsearch.yml
|  |--data
|--kibana
|  |--config
|  |  |--kibana.yml
|--praeco
|  |--bin
|  |  |--elastalert-start.sh
|  |  |--elastic_search_status.sh
|  |--config
|  |  |--api.config.json
|  |  |--elastalert.yaml
|  |--nginx_config
|  |  |--default.conf
|  |  |--nginx.conf
|  |--public
|  |  |--favicon.ico
|  |  |--index.html
|  |  |--js
|  |  |  |--cron-ui.min.js
|  |  |--praeco.config.json
|  |--rule_templates
|  |--rules
```

**Dockerfiles/Dockerfile.elastalert**

```
FROM praecoapp/elastalert-server:latest

USER root

RUN apk update && \
    apk add bash curl && \
    rm -rf /var/cache/apk/*

ADD praeco/bin/elastalert-start.sh /usr/local/bin/
ADD praeco/bin/elastic_search_status.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/elastalert-start.sh 
RUN chmod +x /usr/local/bin/elastic_search_status.sh

USER node

ENTRYPOINT ["/usr/local/bin/elastalert-start.sh"]
```

**docker-compose.yml**

```
version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx512m
      - discovery.type=single-node
    restart: always
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 180s

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s
 
  elastalert:
    container_name: elastalert
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.elastalert
    image: elastalert-server:3.0.0
    ports:
      - 3030:3030
      - 3333:3333
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./praeco/config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./praeco/config/api.config.json:/opt/elastalert-server/config/config.json
      - ./praeco/rules:/opt/elastalert/rules
      - ./praeco/rule_templates:/opt/elastalert/rule_templates
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s

  praeco:
    container_name: praeco
    image: praecoapp/praeco:latest
    ports:
      - 8080:8080
    depends_on:
      - elastalert
    restart: always
    volumes:
      - ./praeco/public/praeco.config.json:/var/www/html/praeco.config.json
      - ./praeco/nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./praeco/nginx_config/default.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
        interval: 30s
        timeout: 15s
        retries: 3
        start_period: 200s
```


**es/config/elasticsearch.yml**

```
cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
```

**kibana/config/kibana.yml**

```
server.name: kibana
server.host: "0"
elasticsearch.hosts: http://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
```

**praeco/bin/elastalert-start.sh**

```
#!/bin/bash

set -e

echo "Giving Elasticsearch at $ELASTICSEARCH_URL time to start..."

elastic_search_status.sh

echo "Starting ElastAlert!"
npm start
```

**praeco/bin/elastic_search_status.sh**

```
#!/bin/bash

set -e

if [ $# -gt 0 ]; then
  ES_URL="$1"
elif [[ -n $ELASTICSEARCH_URL ]]; then
  ES_URL="$ELASTICSEARCH_URL"
elif [[ -n $ES_HOST ]] && [[ -n $ES_PORT ]]; then
  ES_URL="http://$ES_HOST:$ES_PORT"
else
  ES_URL="http://elasticsearch:9200"
fi

until [[ "$(curl -fsSL "$ES_URL/_cat/health?h=status" | sed -r 's/^[[:space:]]+|[[:space:]]+$//g')" =~ ^(yellow|green)$ ]]; do
  # printf '+' >&2
  sleep 1
done

echo "Elasticsearch is up and healthy at "$ES_URL"" >&2
```

**praeco/config/api.config.json**

Default settings

```
{
  "appName": "elastalert-server",
  "port": 3030,
  "wsport": 3333,
  "elastalertPath": "/opt/elastalert",
  "verbose": false,
  "es_debug": false,
  "debug": false,
  "rulesPath": {
    "relative": true,
    "path": "/rules"
  },
  "templatesPath": {
    "relative": true,
    "path": "/rule_templates"
  },
  "es_host": "elasticsearch",
  "es_port": 9200,
  "es_username": "",
  "es_password": "",
  "es_ssl": false,
  "writeback_index": "praeco_elastalert_status"
}
```

**praeco/config/elastalert.yaml**

Default settings

```
# The elasticsearch hostname for metadata writeback
# Note that every rule can have its own elasticsearch host
es_host: elasticsearch

# The elasticsearch port
es_port: 9200

# This is the folder that contains the rule yaml files
# Any .yaml file will be loaded as a rule
rules_folder: rules

# How often ElastAlert will query elasticsearch
# The unit can be anything from weeks to seconds
run_every:
  seconds: 60

# ElastAlert will buffer results from the most recent
# period of time, in case some log sources are not in real time
buffer_time:
  minutes: 1

# Optional URL prefix for elasticsearch
#es_url_prefix: elasticsearch

# Connect with TLS to elasticsearch
#use_ssl: True

# Verify TLS certificates
#verify_certs: True

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for elasticsearch
#es_username: someusername
#es_password: somepassword

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: praeco_elastalert_status

# If an alert fails for some reason, ElastAlert will retry
# sending the alert until this time period has elapsed
alert_time_limit:
  days: 2

skip_invalid: True

profile: default
```

**praeco/public/praeco.config.json**

Default settings

```
{
  "appUrl": "http://127.0.0.1:8080",
  "errorLoggerUrl": "",
  "hidePreconfiguredFields": []
}
```

**setting**

```
cd /home/sano/dkwork2/es
chmod 777 es/data
chmod -R 777 praeco/rules praeco/rule_templates
docker-compose up -d
```
