### ISSUE TITLE
Does this support Elasticsearch 6.X ?

### ISSUE THREAD

**Issue by Mugen1991** [bitsensor/elastalert#36]
Using the docker Container with kibana and elasticsearch 6.2 sadly there is a problem with my rules.

The following Rule 

```
name: Metricbeat CPU Spike Rule
type: metric_aggregation

index: metricbeat-*

buffer_time:  
  minutes: 1

metric_agg_key: system.cpu.total.pct
metric_agg_type: avg
query_key: beat.hostname
doc_type: doc

bucket_interval:
  minutes: 1

sync_bucket_interval: true
#allow_buffer_time_overlap: true
#use_run_every_query_size: true

min_threshold: 0.0
max_threshold: 1.0

filter:
- term:
    metricset.name: "cpu"

# The debug alert is use when a match is found
alert:
  - "hipchat"

hipchat_auth_token: coensored
hipchat_room_id: "coensored"
hipchat_domain: coensored
```

raises the following error ; 

```
Successfully loaded Metricbeat CPU Spike Rule



Would have written the following documents to writeback index (default is elastalert_status):

elastalert_error - {'message': "Error running query: TransportError(400, u'illegal_argument_exception', u'No search type for [count]')", 'traceback': ['Traceback (most recent call last):', '  File "elastalert/elastalert.py", line 518, in get_hits_aggregation', '    ignore_unavailable=True', '  File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 73, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 623, in search', "    doc_type, '_search'), params=params, body=body)", '  File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 312, in perform_request', '    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)', '  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 90, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 125, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: TransportError(400, u'illegal_argument_exception', u'No search type for [count]')"], 'data': {'rule': 'Metricbeat CPU Spike Rule'}}
```

Have I done something wrong with my config ?
