### ISSUE TITLE
Container error

### ISSUE THREAD

**Issue by lecooliver** [bitsensor/elastalert#49]
I'm using the version **0.0.14**.

**docker-compose.yml**:
```
version: '2'

services: 

  elastalert:
    container_name: elastalert
    image: bitsensor/elastalert:latest
    volumes:
      - ./config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./config/config.json:/opt/elastalert-server/config/config.json
      - ./config/auth.yaml:/opt/elastalert/auth.yaml
      - ./rules:/opt/elastalert/rules
      - ./rule_templates:/opt/elastalert/rule_templates
    ports:
      - 3030:3030
    build: .
    restart: always


```
**docker container ls**:
```
CONTAINER ID        IMAGE                         COMMAND             CREATED             STATUS                  PORTS                    NAMES
1ab2ccec9535        bitsensor/elastalert:latest   "npm start"         1 second ago        Up Less than a second   0.0.0.0:3030->3030/tcp   elastalert
```

**docker-compose logs**:
```
elastalert    | 
elastalert    | > @bitsensor/elastalert@0.0.14 start /opt/elastalert-server
elastalert    | > sh ./scripts/start.sh
elastalert    | 
elastalert    | /opt/elastalert-server/src/index.js:1
elastalert    | (function (exports, require, module, __filename, __dirname) { import ElastalertServer from './elastalert_server';
elastalert    |                                                                      ^^^^^^^^^^^^^^^^
elastalert    | 
elastalert    | SyntaxError: Unexpected identifier
elastalert    |     at new Script (vm.js:79:7)
elastalert    |     at createScript (vm.js:251:10)
elastalert    |     at Object.runInThisContext (vm.js:303:10)
elastalert    |     at Module._compile (internal/modules/cjs/loader.js:657:28)
elastalert    |     at loader (/opt/elastalert-server/node_modules/babel-register/lib/node.js:144:5)
elastalert    |     at Object.require.extensions.(anonymous function) [as .js] (/opt/elastalert-server/node_modules/babel-register/lib/node.js:154:7)
elastalert    |     at Module.load (internal/modules/cjs/loader.js:599:32)
elastalert    |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
elastalert    |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
elastalert    |     at Module.require (internal/modules/cjs/loader.js:637:17)
```
