### ISSUE TITLE
Elastalert keeps alerting without reason

### ISSUE THREAD

**Issue by badsector3** [bitsensor/elastalert#54]
I have the lates elastalert-server installed in docker. I created rule:
```
# Host down = metricbeat missing

# (Optional)
# Elasticsearch host
es_host: 10.x.x.x

# (Optional)
# Elasticsearch port
es_port: 9200

# (OptionaL) Connect with SSL to Elasticsearch
#use_ssl: True

# (Optional) basic-auth username and password for Elasticsearch
#es_username: someusername
#es_password: somepassword

# (Required)
# Rule name, must be unique
name: Metricbeat down - srv01

# (Required)
# Type of alert.
type: flatline
threshold: 1
timeframe:
  seconds: 60

# (Required)
# Index to search, wildcard supported
index: metricbeat-*

# (Required)
# A list of Elasticsearch filters used for find events
# These filters are joined with AND and nested in a filtered query
# For more info: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl.html
filter:
- bool:
    filter:
      - term:
          host: "srv01"

# Alert-text
alert_text: "Metricbeat down: ---srv01---"

# Send a maximum of 1 alert every 10 minutes
realert:
  minutes: 10

# (Required)
# The alert is use when a match is found
alert:
- "email"

# (required, email specific)
# a list of email addresses to send alerts to
email:
 - "support@example.com"
```

ELK 6.4.3
bitsensor/elastalert:latest

If I trigger following in Dev Tool in Kibana
```
GET /_search
{
  "query": {
    "bool": {
      "must": [
        { "match": {
          "host": "srv01"
        }}
      ]
    }
  }
}
```
I am getting:
```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 41,
    "successful": 41,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
```

I can see the server srv01 in kibana so the metricbeat is woking fine but I keep getting alerts.
Any idea how to troubleshoot the issue?

Thanks
