### ISSUE TITLE
Unable to start elastalert via docker-compose file

### ISSUE THREAD

**Issue by joshrideshark** [bitsensor/elastalert#68]
**Me docker-compose.yml section for elastalert looks as follows:**
```
  elastalert:
    build:
      context: elastalert/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elastalert/config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./elastalert/config/elastalert-test.yaml:/opt/elastalert/config-test.yaml
      - ./elastalert/config/config.json:/opt/elastalert-server/config/config.json
      - ./elastalert/rules:/opt/elastalert/rules
      - ./elastalert/rule_templates:/opt/elastalert/rule_templates
    ports:
      - 3030:3030
    networks:
      - elk
    depends_on:
      - elasticsearch

```
**When running ` docker-compose up --build` I get the following error:**

```
> @bitsensor/elastalert@1.0.0 start /opt/elastalert-server
> sh ./scripts/start.sh

./scripts/start.sh: line 2:
bunyan: error: unknown output mode: "short
 events.js:173
       throw er; // Unhandled 'error' event
       ^

 Error: write EPIPE
     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:66:16)
 Emitted 'error' event at:
     at errorOrDestroy (internal/streams/destroy.js:98:12)
     at onwriteError (_stream_writable.js:436:5)
     at onwrite (_stream_writable.js:461:5)
     at _destroy (internal/streams/destroy.js:40:7)
     at Socket.dummyDestroy [as _destroy] (internal/process/stdio.js:5:34)
     at Socket.destroy (internal/streams/destroy.js:32:8)
     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:67:12)
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! @bitsensor/elastalert@1.0.0 start: `sh ./scripts/start.sh`
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the @bitsensor/elastalert@1.0.0 start script.
 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

 npm ERR! A complete log of this run can be found in:
 npm ERR!     /root/.npm/_logs/2019-01-22T17_00_13_914Z-debug.log
```

**I believe this issue was already mentioned here: https://github.com/bitsensor/elastalert/issues/49 but never solved**
